"default": true # Default state for all rules
"MD013": false # Disable rule for line length
"MD033": false # Disable rule banning inline HTML
"MD001": false # Allow heading increments (needed for CHANGELOGs)
"MD024": false # Allow duplicate headings (needed for CHANGELOGs)
"MD025": false # Allow multiple H1 headings (needed for CHANGELOGs)
"MD037": false # Allow spaces in emphasis markers
